### PR TITLE
CNFT1-3040 Index Event IDs for Patient Search P2

### PR DESCRIPTION
**Pull request by stevegsa**
## Description

Please include a summary of the changes and any key information a reviewer may need.

## Tickets

* [CNFT1-3040](https://cdc-nbs.atlassian.net/browse/CNFT1-3040)

## Checklist before requesting a review
- [x] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

[CNFT1-3040]: https://cdc-nbs.atlassian.net/browse/CNFT1-3040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by adamloup-enquizit — COMMENTED** [review]
question:  I am seeing a lot of blank values or values like this `,,,,` should blank `root_extension_txt` be excluded?

**Comment by stevegsa** [comment]
> question: I am seeing a lot of blank values or values like this `,,,,` should blank `root_extension_txt` be excluded?

I saw that too.  I looked at entity_id and saw blank root_extension_txts.  Would production ever have entries like that?  I guess it wouldn't hurt to exclude them

**Comment by adamloup-enquizit** [comment]
> > question: I am seeing a lot of blank values or values like this `,,,,` should blank `root_extension_txt` be excluded?
> 
> I saw that too. I looked at entity_id and saw blank root_extension_txts. Would production ever have entries like that? I guess it wouldn't hurt to exclude them

I was getting those values when entering the IDs in an investigation so there will 100% be blanks in production data 😄

**Review by adamloup-enquizit — APPROVED** [review]
👍 📇 👨‍⚕️

**Review by mpeels — APPROVED** [review]

**Pull request merged**
