### PR TITLE
CNFT1-3392: Identification section for basic patient form

### PR DESCRIPTION
**Pull request by joeaxcdw**
## Description

Added the component for the Identification section for the new basic add patient form.

image

## Tickets

* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3392)

## Checklist before requesting a review
- [X] PR focuses on a single story
- [X] Code has been fully tested to meet acceptance criteria
- [X] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [X] All new functions/classes/components reasonably small
- [X] Functions/classes/components focused on one responsibility
- [X] Code easy to understand and modify (clarity over concise/clever)
- [X] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [X] PR does not contain hardcoded values (Uses constants)
- [X] All code is covered by unit or feature tests

### CODE REVIEW

**Comment by alaapbharadwaj** [comment]
Issue: Picture in PR summary shows the addition of "* All required fields for additional information", doesn't look like this in the figma design. 
Screenshot 2024-12-12 at 11 49 47 AM

**Comment by alaapbharadwaj** [comment]
> Issue: Picture in PR summary shows the addition of "* All required fields for additional information", doesn't look like this in the figma design. Screenshot 2024-12-12 at 11 49 47 AM

Actually there seems to be some inconsistency with the "Basic form - default" and "Basic form - filled in". Not sure which is the correct design for the Identification block.

**Comment by joeaxcdw** [comment]
> Actually there seems to be some inconsistency with the "Basic form - default" and "Basic form - filled in". Not sure which is the correct design for the Identification block.

I'll call that out in the story. But that section has required fields so I imagine they want it there.

**Comment by hclarkEnq** [comment]
Screenshot 2024-12-12 at 12 13 37 PM
One small design fix we might want to consider when the type inline error shows is this `select` default data displaying cut off in the bottom of the word

**Comment by joeaxcdw** [comment]
> One small design fix we might want to consider when the type inline error shows is this `select` default data displaying cut off in the bottom of the word

This looks to be the case in the other sections and in the extended form too. I changed the border-width to 2 just to see and it fixed the issue but it may not be what the designers want. I'll bring this up to design team and see if they want to create a bug for this.

**Review by adamloup-enquizit — APPROVED** [review]
👍 Looks good

**Review by stevegsa — APPROVED** [review]

**Pull request merged**
