### PR TITLE
Cypress automation introduction to Patient Search feature and reusabl…

### PR DESCRIPTION
**Pull request by GangulaMounika**
Added Patient search feature and a reusable common file to Cypress Automation.

### CODE REVIEW

**Review by mpeels — APPROVED** [review]
The existing `Search.feature` spec fails. Not sure if it needs updated or removed as it is attempting to navigate to a removed `simple search` page 

Test results:

image

**Comment by mpeels** [comment]
Oh, missed this on first pass. It would be nice to add `cypress/screenshots` and `cypress/videos` folders to `.gitignore`

**Comment by GangulaMounika** [comment]
> The existing `Search.feature` spec fails. Not sure if it needs updated or removed as it is attempting to navigate to a removed `simple search` page
> 
> Test results:
> 
> image

It was an old spec that was failing from before and yes we don't need that spec file anymore
image

**Comment by GangulaMounika** [comment]
> Oh, missed this on first pass. It would be nice to add `cypress/screenshots` and `cypress/videos` folders to `.gitignore`

Yes, created a .gitignore in patient-search folder and added it there.

**Pull request merged**
