### PR TITLE
Make pagination background transparent on search page

### PR DESCRIPTION
**Pull request by rkrusselenq**
## Description

Quick ui fix to make the pagination buttons transparent on the patient search page.

## Tickets

* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-1926)

## Checklist before requesting a review
- [x] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

### CODE REVIEW

**Review by hclarkEnq — DISMISSED** [review]

**Review by adamloup-enquizit — COMMENTED** [review]
question:  Should this be a global change to all `Pagination` components?  Advanced Search may just be the only example where the component is not on a white background.

**Comment by rkrusselenq** [comment]
> question: Should this be a global change to all `Pagination` components? Advanced Search may just be the only example where the component is not on a white background.

Yeah probably. I thought the same thing but the Pagination component comes from Trussworks, so i'm not sure if there's a way to change it globally.

**Comment by adamloup-enquizit** [comment]
> > question: Should this be a global change to all `Pagination` components? Advanced Search may just be the only example where the component is not on a white background.
> 
> Yeah probably. I thought the same thing but the Pagination component comes from Trussworks, so i'm not sure if there's a way to change it globally.

Overrides to Trussworks components or USWDS styles to match our design system have been added to a [specific stylesheet](https://github.com/CDCgov/NEDSS-Modernization/blob/main/apps/modernization-ui/src/styles/_uswds.scss).  We might be able to add the background to the `usa-paginiation` class so it would affect all paginiation components

**Comment by rkrusselenq** [comment]
> > > question: Should this be a global change to all `Pagination` components? Advanced Search may just be the only example where the component is not on a white background.
> > 
> > 
> > Yeah probably. I thought the same thing but the Pagination component comes from Trussworks, so i'm not sure if there's a way to change it globally.
> 
> Overrides to Trussworks components or USWDS styles to match our design system have been added to a [specific stylesheet](https://github.com/CDCgov/NEDSS-Modernization/blob/main/apps/modernization-ui/src/styles/_uswds.scss). We might be able to add the background to the `usa-paginiation` class so it would affect all paginiation components

Thanks! now fixed.

**Review by adamloup-enquizit — APPROVED** [review]
Nice!

**Review by hclarkEnq — APPROVED** [review]

**Pull request merged**
