### PR TITLE
updating welcome title and fixing birth order input field

### PR DESCRIPTION
**Pull request by hclarkEnq**
## Description

**Birth order field should only allow a numeric value.
**Update the title to match the updated designs
## Tickets

* [CNFT1-2291](https://cdc-nbs.atlassian.net/browse/CNFT1-2291)
* [CNFT1-2297](https://cdc-nbs.atlassian.net/browse/CNFT1-2297)
## Checklist before requesting a review
- [ ] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

[CNFT1-2291]: https://cdc-nbs.atlassian.net/browse/CNFT1-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2297]: https://cdc-nbs.atlassian.net/browse/CNFT1-2297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by adamloup-enquizit** [comment]
Isn't there a bug for only allowing numbers for birth order?

**Comment by hclarkEnq** [comment]
> Isn't there a bug for only allowing numbers for birth order?

yeah and im including the fix in this pr to only take numbers, the bug is already in this sprint so Im working on it now and including in this pr with the title change since there both pretty small changes

**Comment by hclarkEnq** [comment]
> > Isn't there a bug for only allowing numbers for birth order?
> 
> yeah and im including the fix in this pr to only take numbers, the bug is already in this sprint so Im working on it now and including in this pr with the title change since there both pretty small changes

Just updated the pr description to show both tickets within

**Review by adamloup-enquizit — APPROVED** [review]
I feel for the parents of anyone with a 5 digit birth order

**Review by rkrusselenq — APPROVED** [review]

**Pull request merged**
