### PR TITLE
adding search ui fixes

### PR DESCRIPTION
**Pull request by hclarkEnq**
## Description

space between the status text and the checkboxes in patient search, tooltip icon button

## Tickets

* [CNFT1-2927](https://cdc-nbs.atlassian.net/browse/CNFT1-2927)

## Checklist before requesting a review
- [x] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

[CNFT1-2927]: https://cdc-nbs.atlassian.net/browse/CNFT1-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by adamloup-enquizit — COMMENTED** [review]
[Figma](https://www.figma.com/design/TVilgvbjEwoYTqtQekVZwJ/NBS-7.x--%3E-Patient-Search-2.0?node-id=2520-24746&t=KzJJviaIoBpTREuJ-0) is showing a gap of 0.5rem here.

image

The changes produce a much larger gap

image


image

**Review by adamloup-enquizit — APPROVED** [review]
👍

**Review by adamloup-enquizit — APPROVED** [review]
👍 Looks good!

**Review by stevegsa — APPROVED** [review]
Thanks for the screenshots 💯

**Pull request merged**
