### PR TITLE
Cnft2 643 view valueset details

### PR DESCRIPTION
**Pull request by rkrusselenq**
Navigate to http://localhost:3000/page-builder/manage/valueset-library.  Now when you click on the down arrow for a row, it should open up to display more details about the value set.

### CODE REVIEW

**Comment by lramakr** [comment]
There are merge conflicts

**Review by lramakr — DISMISSED** [review]
LGTM

**Comment by mpeels** [comment]
Build failure: 
image

**Review by lramakr — APPROVED** [review]
LGTM

**Pull request merged**
